"""
Standalone script to submit the SPK declaration to the verify endpoint.

Usage:
    python3 -m s01e04.register <path-to-result.json>

Reads the declaration_text from a result JSON file generated by main.py.
"""
import json
import sys

from common import get_api_key, load_dotenv, api_post
from endpoints import VERIFY

load_dotenv()
api_key = get_api_key()

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 -m s01e04.register <path-to-result.json>")
        sys.exit(1)

    with open(sys.argv[1], "r", encoding="utf-8") as f:
        data = json.load(f)

    declaration_text = data["declaration_text"]
    print(f"Declaration:\n{declaration_text}\n")

    print("Submitting...")
    try:
        result = api_post(VERIFY, {
            "apikey": api_key,
            "task": "sendit",
            "answer": {"declaration": declaration_text}
        })
        print(f"Response: {result}")
    except Exception as e:
        print(f"Error: {e}")
